[package]
name = "rxrust"
version = "0.1.0"
authors = ["adoo <Adoo@outlook.com>"]
edition = "2018"
description = "A Rust implementation of Reactive Extensions."
keywords = ["reactivex", "rx", "frp"]
license = "MIT"

[dependencies]
futures-preview = "=0.3.0-alpha.18"
lazy_static = "1.3.0"